name: "BBR_OpenAI_Ask"
title: "Ask OpenAI"
category: "Stacks"

docker_image_name: "osexp2000/ubuntu-with-utils"
docker_image_tag: "latest"

inputs:
  prompt:
    type: TEXT
    required: true
  openAiKey:
    type: PASSWORD
    required: true
  openAiModel:
    type: SELECT
    required: true
    default: "gpt-3.5-turbo-instruct"
    options:
      - "gpt-3.5-turbo-instruct"
      - "text-davinci-003"
      - "text-davinci-002"

execute_commands:
  - prompt=$(echo "$prompt" | sed 's/"//g')
  - prompt=$(echo "$prompt" | iconv -t UTF-8)
  - prompt=$(echo -n "$prompt" | tr -d '\n')

  - 'response=$(curl -X POST https://api.openai.com/v1/completions -H "Authorization: Bearer $openAiKey" -H "Content-Type: application/json" -d "{ \"model\": \"$openAiModel\", \"prompt\": \"prompt instructions: remove hidden and special characters in answer, prompt: $prompt\", \"max_tokens\": 50, \"temperature\": 0.3 }" ) '

  - error=$(echo "$response" | jq -r '.error.message')

  - if [ "$error" != null ];
  - then
  - 'echo "OpenAI Error Response: $error"'
  - exit 1
  - fi

  - answer=$(echo "$response" | jq -r '.choices[0].text')
  - answer=$(echo -n "$answer" | tr -d '\n')
  - export OPENAI_ANSWER=$answer

output:
  variables:
    OPENAI_ANSWER:
      example: "Sample answer of OpenAI for your prompt."
      info: "The answer of OpenAI for your prompt"