name: Validate-YAML

on: [push, pull_request, workflow_dispatch]


jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Budddy Actions
        uses: GrantBirki/json-yaml-validate@v2.4.0
        with:
          base_dir: .buddy