name: "BBR_OpenAI_Image"
title: "Create OpenAI Image"
category: "Stacks"

docker_image_name: "osexp2000/ubuntu-with-utils"
docker_image_tag: "latest"

inputs:
  prompt:
    type: TEXT
    required: true
  openAiKey:
    type: PASSWORD
    required: true
  size:
    type: SELECT
    required: true
    default: "1024x1024"
    options:
      - "1024x1024"
      - "1792x1024"
      - "1024x1792"

execute_commands:
  - prompt=$(echo "$prompt" | sed 's/"//g')
  - prompt=$(echo "$prompt" | iconv -t UTF-8)
  - prompt=$(echo -n "$prompt" | tr -d '\n')

  - 'response=$(curl -X POST https://api.openai.com/v1/images -H "Authorization: Bearer $openAiKey" -H "Content-Type: application/json" -d "{ \"prompt\": \"$prompt\" }" ) '

  - error=$(echo "$response" | jq -r '.error.message')

  - if [ "$error" != null ];
  - then
  - 'echo "OpenAI Error Response: $error"'
  - exit 1
  - fi

  - imageUrl=$(echo "$response" | jq -r '.data[0].url')
  - export OPENAI_IMAGE_URL=$imageUrl

output:
  variables:
    OPENAI_IMAGE_URL:
      info: "The URL of the image generated by OpenAI"